name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your repo

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # use your output folder here if needed

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
